const postcodeData = {
    NSW: [
        { suburb: "Sydney", postcode: "2000" },
        { suburb: "The Rocks", postcode: "2000" },
        { suburb: "Barangaroo", postcode: "2000" },
        { suburb: "Darlinghurst", postcode: "2010" },
        { suburb: "Surry Hills", postcode: "2010" },
        { suburb: "Paddington", postcode: "2021" },
        { suburb: "Bondi Beach", postcode: "2026" },
        { suburb: "Bondi Junction", postcode: "2022" },
        { suburb: "Coogee", postcode: "2034" },
        { suburb: "Randwick", postcode: "2031" },
        { suburb: "Maroubra", postcode: "2035" },
        { suburb: "Mascot", postcode: "2020" },
        { suburb: "Rosebery", postcode: "2018" },
        { suburb: "Waterloo", postcode: "2017" },
        { suburb: "Zetland", postcode: "2017" },
        { suburb: "Newtown", postcode: "2042" },
        { suburb: "Enmore", postcode: "2042" },
        { suburb: "Erskineville", postcode: "2043" },
        { suburb: "Alexandria", postcode: "2015" },
        { suburb: "Redfern", postcode: "2016" },
        { suburb: "Chippendale", postcode: "2008" },
        { suburb: "Ultimo", postcode: "2007" },
        { suburb: "Pyrmont", postcode: "2009" },
        { suburb: "Glebe", postcode: "2037" },
        { suburb: "Forest Lodge", postcode: "2037" },
        { suburb: "Annandale", postcode: "2038" },
        { suburb: "Leichhardt", postcode: "2040" },
        { suburb: "Lilyfield", postcode: "2040" },
        { suburb: "Rozelle", postcode: "2039" },
        { suburb: "Balmain", postcode: "2041" },
        { suburb: "Drummoyne", postcode: "2047" },
        { suburb: "Five Dock", postcode: "2046" },
        { suburb: "Ashfield", postcode: "2131" },
        { suburb: "Burwood", postcode: "2134" },
        { suburb: "Strathfield", postcode: "2135" },
        { suburb: "Homebush", postcode: "2140" },
        { suburb: "Concord", postcode: "2137" },
        { suburb: "Rhodes", postcode: "2138" },
        { suburb: "Lidcombe", postcode: "2141" },
        { suburb: "Parramatta", postcode: "2150" },
        { suburb: "Harris Park", postcode: "2150" },
        { suburb: "Granville", postcode: "2142" },
        { suburb: "Merrylands", postcode: "2160" },
        { suburb: "Guildford", postcode: "2161" },
        { suburb: "Auburn", postcode: "2144" },
        { suburb: "Bankstown", postcode: "2200" },
        { suburb: "Punchbowl", postcode: "2196" },
        { suburb: "Lakemba", postcode: "2195" },
        { suburb: "Campsie", postcode: "2194" },
        { suburb: "Canterbury", postcode: "2193" },
        { suburb: "Hurstville", postcode: "2220" },
        { suburb: "Kogarah", postcode: "2217" },
        { suburb: "Rockdale", postcode: "2216" },
        { suburb: "Bexley", postcode: "2207" },
        { suburb: "Brighton-Le-Sands", postcode: "2216" },
        { suburb: "Cronulla", postcode: "2230" },
        { suburb: "Miranda", postcode: "2228" },
        { suburb: "Sutherland", postcode: "2232" },
        { suburb: "Engadine", postcode: "2233" },
        { suburb: "Menai", postcode: "2234" },
        { suburb: "Blacktown", postcode: "2148" },
        { suburb: "Seven Hills", postcode: "2147" },
        { suburb: "Castle Hill", postcode: "2154" },
        { suburb: "Baulkham Hills", postcode: "2153" },
        { suburb: "Kellyville", postcode: "2155" },
        { suburb: "Rouse Hill", postcode: "2155" },
        { suburb: "Penrith", postcode: "2750" },
        { suburb: "Emu Plains", postcode: "2750" },
        { suburb: "St Marys", postcode: "2760" },
        { suburb: "Mount Druitt", postcode: "2770" },
        { suburb: "Windsor", postcode: "2756" },
        { suburb: "Richmond", postcode: "2753" },
        { suburb: "Campbelltown", postcode: "2560" },
        { suburb: "Liverpool", postcode: "2170" },
        { suburb: "Casula", postcode: "2170" },
        { suburb: "Fairfield", postcode: "2165" },
        { suburb: "Wetherill Park", postcode: "2164" },
        { suburb: "Cabramatta", postcode: "2166" },
        { suburb: "Smithfield", postcode: "2164" },
        { suburb: "Moorebank", postcode: "2170" },
        { suburb: "Green Valley", postcode: "2168" },
        { suburb: "Prestons", postcode: "2170" },
        { suburb: "Holsworthy", postcode: "2173" },
        { suburb: "Ingleburn", postcode: "2565" },
        { suburb: "Macquarie Fields", postcode: "2564" },
        { suburb: "Narellan", postcode: "2567" },
        { suburb: "Camden", postcode: "2570" },
        { suburb: "Oran Park", postcode: "2570" },
        { suburb: "Bowral", postcode: "2576" },
        { suburb: "Moss Vale", postcode: "2577" },
        { suburb: "Nowra", postcode: "2541" },
        { suburb: "Wollongong", postcode: "2500" },
        { suburb: "Shellharbour", postcode: "2529" },
        { suburb: "Kiama", postcode: "2533" },
        { suburb: "Newcastle", postcode: "2300" },
        { suburb: "Merewether", postcode: "2291" },
        { suburb: "Hamilton", postcode: "2303" },
        { suburb: "Charlestown", postcode: "2290" },
        { suburb: "Cessnock", postcode: "2325" },
        { suburb: "Maitland", postcode: "2320" },
        { suburb: "Port Macquarie", postcode: "2444" },
        { suburb: "Coffs Harbour", postcode: "2450" },
        { suburb: "Tamworth", postcode: "2340" },
        { suburb: "Armidale", postcode: "2350" },
        { suburb: "Bathurst", postcode: "2795" },
        { suburb: "Orange", postcode: "2800" },
        { suburb: "Dubbo", postcode: "2830" },
        { suburb: "Broken Hill", postcode: "2880" },
        { suburb: "Wollongong", postcode: "2500" },
        { suburb: "North Wollongong", postcode: "2500" },
        { suburb: "Fairy Meadow", postcode: "2519" },
        { suburb: "Towradgi", postcode: "2518" },
        { suburb: "Corrimal", postcode: "2518" },
        { suburb: "Balgownie", postcode: "2519" },
        { suburb: "Tarrawanna", postcode: "2518" },
        { suburb: "Bellambi", postcode: "2518" },
        { suburb: "Russell Vale", postcode: "2517" },
        { suburb: "Woonona", postcode: "2517" },
        { suburb: "Bulli", postcode: "2516" },
        { suburb: "Thirroul", postcode: "2515" },
        { suburb: "Austinmer", postcode: "2515" },
        { suburb: "Coledale", postcode: "2515" },
        { suburb: "Scarborough", postcode: "2515" },
        { suburb: "Helensburgh", postcode: "2508" },
        { suburb: "Stanwell Park", postcode: "2508" },
        { suburb: "Stanwell Tops", postcode: "2508" },
        { suburb: "Otford", postcode: "2508" },
        { suburb: "Port Kembla", postcode: "2505" },
        { suburb: "Warrawong", postcode: "2502" },
        { suburb: "Berkeley", postcode: "2506" },
        { suburb: "Unanderra", postcode: "2526" },
        { suburb: "Figtree", postcode: "2525" },
        { suburb: "Farmborough Heights", postcode: "2526" },
        { suburb: "Mount Saint Thomas", postcode: "2500" },
        { suburb: "Coniston", postcode: "2500" },
        { suburb: "Cringila", postcode: "2502" },
        { suburb: "Primbee", postcode: "2502" },
        { suburb: "Lake Heights", postcode: "2502" },
        { suburb: "Windang", postcode: "2528" },
        { suburb: "Oak Flats", postcode: "2529" },
        { suburb: "Albion Park Rail", postcode: "2527" },
        { suburb: "Kembla Grange", postcode: "2526" },
        { suburb: "Dapto", postcode: "2530" },
        { suburb: "Kanahooka", postcode: "2530" },
        { suburb: "Horsley", postcode: "2530" },
        { suburb: "Avondale", postcode: "2530" },
        { suburb: "Yallah", postcode: "2530" },
        { suburb: "Haywards Bay", postcode: "2530" },
        { suburb: "Calderwood", postcode: "2527" },
        { suburb: "Tullimbar", postcode: "2527" },
        { suburb: "Cordeaux Heights", postcode: "2526" },
    ],
    VIC: [
      { suburb: "Melbourne", postcode: "3000" },
      { suburb: "St Kilda", postcode: "3182" },
      { suburb: "Richmond", postcode: "3121" },
      { suburb: "Southbank", postcode: "3006" },
      { suburb: "Geelong", postcode: "3220" },
      { suburb: "Fitzroy", postcode: "3065" },
      { suburb: "Carlton", postcode: "3053" },
      { suburb: "Brunswick", postcode: "3056" },
      { suburb: "Docklands", postcode: "3008" },
      { suburb: "Prahran", postcode: "3181" },
      { suburb: "South Yarra", postcode: "3141" },
      { suburb: "Footscray", postcode: "3011" },
      { suburb: "Frankston", postcode: "3199" },
      { suburb: "Ballarat", postcode: "3350" },
      { suburb: "Bendigo", postcode: "3550" },
      { suburb: "Dandenong", postcode: "3175" },
      { suburb: "Pakenham", postcode: "3810" },
      { suburb: "Werribee", postcode: "3030" },
      { suburb: "Sunshine", postcode: "3020" },
      { suburb: "Reservoir", postcode: "3073" },
      // +80 more VIC suburbs...
    ],
    QLD: [
      { suburb: "Brisbane City", postcode: "4000" },
      { suburb: "South Brisbane", postcode: "4101" },
      { suburb: "Fortitude Valley", postcode: "4006" },
      { suburb: "Sunnybank", postcode: "4109" },
      { suburb: "Gold Coast", postcode: "4217" },
      { suburb: "Southport", postcode: "4215" },
      { suburb: "Surfers Paradise", postcode: "4217" },
      { suburb: "Cairns", postcode: "4870" },
      { suburb: "Townsville", postcode: "4810" },
      { suburb: "Toowoomba", postcode: "4350" },
      { suburb: "Logan Central", postcode: "4114" },
      { suburb: "Redcliffe", postcode: "4020" },
      { suburb: "Bundaberg", postcode: "4670" },
      { suburb: "Mackay", postcode: "4740" },
      { suburb: "Hervey Bay", postcode: "4655" },
      { suburb: "Ipswich", postcode: "4305" },
      { suburb: "Springfield Lakes", postcode: "4300" },
      { suburb: "Robina", postcode: "4226" },
      { suburb: "Burleigh Heads", postcode: "4220" },
      { suburb: "Maroochydore", postcode: "4558" },
      // +80 more QLD suburbs...
    ],
    SA: [
      { suburb: "Adelaide", postcode: "5000" },
      { suburb: "Glenelg", postcode: "5045" },
      { suburb: "Norwood", postcode: "5067" },
      { suburb: "Unley", postcode: "5061" },
      { suburb: "Prospect", postcode: "5082" },
      { suburb: "Henley Beach", postcode: "5022" },
      { suburb: "Semaphore", postcode: "5019" },
      { suburb: "Mawson Lakes", postcode: "5095" },
      { suburb: "Salisbury", postcode: "5108" },
      { suburb: "Port Adelaide", postcode: "5015" },
      { suburb: "Mount Gambier", postcode: "5290" },
      { suburb: "Murray Bridge", postcode: "5253" },
      { suburb: "Victor Harbor", postcode: "5211" },
      { suburb: "Whyalla", postcode: "5600" },
      { suburb: "Elizabeth", postcode: "5112" },
      { suburb: "Tea Tree Gully", postcode: "5091" },
      { suburb: "Goodwood", postcode: "5034" },
      { suburb: "Burnside", postcode: "5066" },
      { suburb: "Happy Valley", postcode: "5159" },
      { suburb: "Port Lincoln", postcode: "5606" },
      // +80 more SA suburbs...
    ],
    WA: [
      { suburb: "Perth", postcode: "6000" },
      { suburb: "Fremantle", postcode: "6160" },
      { suburb: "Subiaco", postcode: "6008" },
      { suburb: "Joondalup", postcode: "6027" },
      { suburb: "Cottesloe", postcode: "6011" },
      { suburb: "Mandurah", postcode: "6210" },
      { suburb: "Bunbury", postcode: "6230" },
      { suburb: "Albany", postcode: "6330" },
      { suburb: "Rockingham", postcode: "6168" },
      { suburb: "Armadale", postcode: "6112" },
      { suburb: "Midland", postcode: "6056" },
      { suburb: "Baldivis", postcode: "6171" },
      { suburb: "Karratha", postcode: "6714" },
      { suburb: "Broome", postcode: "6725" },
      { suburb: "Geraldton", postcode: "6530" },
      { suburb: "Busselton", postcode: "6280" },
      { suburb: "Ellenbrook", postcode: "6069" },
      { suburb: "Morley", postcode: "6062" },
      { suburb: "Scarborough", postcode: "6019" },
      { suburb: "South Perth", postcode: "6151" },
      // +80 more WA suburbs...
    ],
    TAS: [
      { suburb: "Hobart", postcode: "7000" },
      { suburb: "Launceston", postcode: "7250" },
      { suburb: "Devonport", postcode: "7310" },
      { suburb: "Burnie", postcode: "7320" },
      { suburb: "Glenorchy", postcode: "7010" },
      { suburb: "Kingston", postcode: "7050" },
      { suburb: "Sandy Bay", postcode: "7005" },
      { suburb: "New Norfolk", postcode: "7140" },
      { suburb: "Ulverstone", postcode: "7315" },
      { suburb: "Bellerive", postcode: "7018" },
      { suburb: "Howrah", postcode: "7018" },
      { suburb: "West Hobart", postcode: "7000" },
      { suburb: "Lenah Valley", postcode: "7008" },
      { suburb: "Prospect", postcode: "7250" },
      { suburb: "Blackmans Bay", postcode: "7052" },
      { suburb: "Bridgewater", postcode: "7030" },
      { suburb: "Riverside", postcode: "7250" },
      { suburb: "Margate", postcode: "7054" },
      { suburb: "Montrose", postcode: "7010" },
      { suburb: "Moonah", postcode: "7009" },
      // +80 more TAS suburbs...
    ],
    ACT: [
      { suburb: "Canberra City", postcode: "2600" },
      { suburb: "Belconnen", postcode: "2617" },
      { suburb: "Woden", postcode: "2606" },
      { suburb: "Tuggeranong", postcode: "2900" },
      { suburb: "Gungahlin", postcode: "2912" },
      { suburb: "Kingston", postcode: "2604" },
      { suburb: "Braddon", postcode: "2612" },
      { suburb: "Phillip", postcode: "2606" },
      { suburb: "Narrabundah", postcode: "2604" },
      { suburb: "Lyneham", postcode: "2602" },
      // +90 more ACT suburbs...
    ],
    NT: [
      { suburb: "Darwin", postcode: "0800" },
      { suburb: "Palmerston", postcode: "0830" },
      { suburb: "Katherine", postcode: "0850" },
      { suburb: "Alice Springs", postcode: "0870" },
      { suburb: "Casuarina", postcode: "0810" },
      { suburb: "Nightcliff", postcode: "0810" },
      { suburb: "Humpty Doo", postcode: "0836" },
      { suburb: "Larrakeyah", postcode: "0820" },
      { suburb: "Tennant Creek", postcode: "0860" },
      { suburb: "Coolalinga", postcode: "0835" },
      // +90 more NT suburbs...
    ],
  };
  
  export default postcodeData;
  