name: Full-Stack CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Run backend lint
        run: npm run lint
        working-directory: backend

      - name: Download Code Climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
        working-directory: backend

      - name: Code Climate before-build (backend)
        run: ./cc-test-reporter before-build
        working-directory: backend

      - name: Run backend tests
        run: npm run test -- --coverage
        working-directory: backend

      - name: Code Climate after-build (backend)
        run: ./cc-test-reporter after-build --exit-code $?
        working-directory: backend
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Run frontend lint
        run: npm run lint
        working-directory: frontend

      - name: Download Code Climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
        working-directory: frontend

      - name: Code Climate before-build (frontend)
        run: ./cc-test-reporter before-build
        working-directory: frontend

      - name: Run frontend tests
        run: npm run test -- --coverage --watchAll=false
        working-directory: frontend

      - name: Code Climate after-build (frontend)
        run: ./cc-test-reporter after-build --exit-code $?
        working-directory: frontend
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Build React app using Vite
        run: npm run build
        working-directory: frontend

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/
