name: Full-Stack CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Run backend lint
        run: npm run lint
        working-directory: backend

      - name: Download Code Climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
        working-directory: backend

      - name: Code Climate before-build (backend)
        run: ./cc-test-reporter before-build
        working-directory: backend

      - name: Run backend tests
        run: npm run test -- --coverage
        working-directory: backend

      - name: Code Climate after-build (backend)
        run: ./cc-test-reporter after-build --exit-code $?
        working-directory: backend
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install user dependencies
        run: npm install
        working-directory: user

      - name: Run frontend lint
        run: npm run lint
        working-directory: user

      - name: Download Code Climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
        working-directory: user

      - name: Code Climate before-build (frontend)
        run: ./cc-test-reporter before-build
        working-directory: user

      - name: Run frontend tests
        run: npm run test -- --coverage
        working-directory: user

      - name: Format code coverage (frontend)
        run: ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json
        working-directory: user
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Code Climate after-build (frontend)
        run: ./cc-test-reporter after-build --exit-code $?
        working-directory: user
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Build React app using Vite
        run: npm run build
        working-directory: user

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: user/dist/

  organiser:
    name: Organiser (Next.js) CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: organiser/package-lock.json

      - name: Install organiser dependencies
        run: npm install
        working-directory: organiser

      - name: Run organiser lint
        run: npm run lint
        working-directory: organiser

      - name: Download Code Climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
        working-directory: organiser

      - name: Code Climate before-build (organiser)
        run: ./cc-test-reporter before-build
        working-directory: organiser

      - name: Run organiser tests
        run: npm run test -- --coverage
        working-directory: organiser

      - name: Format code coverage (organiser)
        run: ./cc-test-reporter format-coverage coverage/lcov.info -t lcov -o coverage/codeclimate.json
        working-directory: organiser
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Upload coverage to Code Climate (organiser)
        run: ./cc-test-reporter upload-coverage -i coverage/codeclimate.json
        working-directory: organiser
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Build Next.js app
        run: npm run build
        working-directory: organiser

      - name: Upload production build (organiser)
        uses: actions/upload-artifact@v4
        with:
          name: organiser-build
          path: organiser/.next/
